# Generated by Django 3.2.4 on 2021-07-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Library_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=180)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
